poetry.lock
pyproject.toml

Add poetry.lock file.

---

.github/workflows/test.yml

Remove permission token.

---

.pre-commit-config.yaml
ansys/tools/repo_sync/repo_sync.py
poetry.lock
tests/test_workflow.py

If no manifest is provided, all files are copied.

If no manifest is provided, all files are copied.

---

.github/workflows/release.yml

Change the way the package is built.

Change the way the package is built.

---

.github/workflows/release.yml

Change the environment variable in release workflow.

Change the environment variable in release workflow.

---

ansys/tools/repo_sync/__init__.py
poetry.lock
pyproject.toml

Change the name of the package.

Change the name of the package.

---

ansys/tools/repo_sync/repo_sync.py

Print stdout and stderr to get info while deploying the tool.

Print stdout and stderr to get info while deploying the tool.

---

ansys/tools/repo_sync/repo_sync.py

Set the local username.

---

ansys/tools/repo_sync/repo_sync.py

Set the credentials locally.

---

ansys/tools/repo_sync/repo_sync.py

Set the remote url.

---

poetry.lock
pyproject.toml

Upgrade packages version to fix vulnerabilities from urlllib3.

Upgrade packages version to fix vulnerabilities from urlllib3.

---

.github/dependabot.yml

Add dependabot.

---

ansys/tools/repo_sync/__main__.py
ansys/tools/repo_sync/repo_sync.py
tests/test_workflow.py

Add an argument to specify the name of the branch to check out.

Add an argument to specify the name of the branch to check out.

---

ansys/tools/repo_sync/repo_sync.py

Add a parameter to specify the folder to contain the files.

Add a parameter to specify the folder to contain the files.

---

ansys/tools/repo_sync/__main__.py

Add the output_path parameter.

Add the output_path parameter.

---

ansys/tools/repo_sync/__main__.py

Remove the parameter exists for output_path.

Remove the parameter exists for output_path.

---

ansys/tools/repo_sync/repo_sync.py

Force the copy over existing files.

Force the copy over existing files.

---

pyproject.toml

Fix entry point for the CLI

---

README.rst
src/ansys/tools/repo_sync/__main__.py

feat: improve documentation

---

.github/dependabot.yml

feat: update dependabot config

---

.github/workflows/ci_cd.yml
README.rst

Update codecov action to include token and badge call

maint: codecov token and badge update

---

pyproject.toml
src/ansys/tools/repo_sync/__main__.py
src/ansys/tools/repo_sync/repo_sync.py
tests/test_sync.py

Create a flag to delete content inside target directory

feat: cleanup target directory on demand

---

src/ansys/tools/repo_sync/__main__.py
src/ansys/tools/repo_sync/repo_sync.py
tests/assets/manifest_proto_and_init.txt
tests/test_sync.py

Perform deletion of files based on manifest.

feat: manifest-based deletion

---

.github/workflows/ci_cd.yml
pyproject.toml
src/ansys/tools/repo_sync/__init__.py

feat: bump to Python 3.12 and drop 3.8

---

.pre-commit-config.yaml
src/ansys/tools/repo_sync/__init__.py
src/ansys/tools/repo_sync/__main__.py
src/ansys/tools/repo_sync/repo_sync.py
tests/__init__.py
tests/assets/ansys/api/test/v0/hello_world.py
tests/assets/ansys/api/test/v0/test.proto
tests/conftest.py
tests/test_sync.py

feat: add license header hook

---

.github/workflows/ci_cd.yml

As title says. Implementing vulnerabilities check

feat: add vulnerabilities check

---

AUTHORS
CONTRIBUTORS.md

fix: files
